### ISSUE TITLE
Sorting on volume is not working correct

### ISSUE THREAD

**Issue by fredpook** [matteoantoci/ch-companion#3]
When choosing BINANCE, BTC, 50 coins and no other options, very low volume coins are in the output.
For instance today YOYO  is selected and that is way down the list with a volume 147

**Comment by fredpook** [comment]
I gone tru the code and there is noting wrong with the sorting on volume. tested with the UI on https://www.tradingview.com/cryptocurrency-signals/ and posted to the API. same results as the ch companion output.

There must be a big difference in the meaning of "volume" between TV and binance. I think TV has a concept of "trading volume" but don't know what that means.

Maybe the difference between the 2 should be in the README?

**Comment by matteoantoci** [comment]
Thanks for the investigation, unfortunately I don't know which data TV is using =(

About the difference I mentioned it in the "disclaimer" section. 

Cheers!
